In [136]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import joblib

In [137]:
df = pd.read_csv("laptopCleanData.csv")

In [138]:
df.columns

Index(['brand_name', 'name', 'processor_type', 'processor_brand',
       'generations', 'ram', 'storage_capacity_gb', 'have_ssd', 'have_hdd',
       'graphics_capacity', 'price', 'display_size_inch', 'display_type',
       'color'],
      dtype='object')

In [139]:
df.head()

,brand_name,name,processor_type,processor_brand,generations,ram,storage_capacity_gb,have_ssd,have_hdd,graphics_capacity,price,display_size_inch,display_type,color
0,lenovo,Lenovo IdeaPad D330 10IGL Intel CDC N4020 4GB ...,Intel Celeron,Intel,Not Applicable,4,128,False,True,-1,34500,10.1,HD,Mineral Grey
1,hp,HP 15s-eq1578AU AMD Athlon Silver 3050U 8GB 2...,AMD Athlon,AMD,Not Applicable,8,256,True,False,-1,46500,15.6,FHD,Silver
2,acer,Acer Aspire 3 A315-510P-38RH (13th Gen Standar...,Intel Core i3,Intel,13th,8,512,True,False,-1,49800,15.6,FHD,Pure Silver
3,lenovo,Lenovo IdeaPad 1 15ADA7 AMD Ryzen 3 3250U 8GB ...,AMD Ryzen 3,AMD,Not Applicable,8,512,True,False,-1,49900,15.6,FHD,Cloud Grey
4,lenovo,Lenovo IdeaPad Slim 3i 15ITL 11th Gen Intel Co...,Intel Core i3,Intel,11th,4,256,True,False,-1,51400,15.6,FHD,Arctic Grey

In [140]:
df.tail()

,brand_name,name,processor_type,processor_brand,generations,ram,storage_capacity_gb,have_ssd,have_hdd,graphics_capacity,price,display_size_inch,display_type,color
346,apple,Apple Macbook Pro (Early 2023) Apple M2 Max Ch...,Apple M2,Apple,Not Applicable,32,2048,True,False,-1,495000,16.2,Liquid Retina XDR,Space Gray
347,apple,Apple Macbook Pro (Late 2023) Apple M3 Max 48G...,Apple M3,Apple,Not Applicable,48,1024,True,False,-1,538000,16.2,Liquid Retina XDR,Silver
348,apple,Apple Macbook Pro (Late 2023) Apple M3 Max 48G...,Apple M3,Apple,Not Applicable,48,1024,True,False,-1,540000,16.2,Liquid Retina XDR,Space Black
349,apple,Apple Macbook Pro (Late 2023) Apple M3 Max 64G...,Apple M3,Apple,Not Applicable,64,4096,True,False,-1,765000,16.2,Liquid Retina XDR,Space Black
350,apple,Apple Macbook Pro (Late 2023) Apple M3 Max 128...,Apple M3,Apple,Not Applicable,128,8192,True,False,-1,1095000,16.2,Liquid Retina XDR,Space Black

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand_name           351 non-null    object
 1   name                 351 non-null    object
 2   processor_type       351 non-null    object
 3   processor_brand      351 non-null    object
 4   generations          351 non-null    object
 5   ram                  351 non-null    int64
 6   storage_capacity_gb  351 non-null    int64
 7   have_ssd             351 non-null    bool
 8   have_hdd             351 non-null    bool
 9   graphics_capacity    351 non-null    int64
 10  price                351 non-null    int64
 11  display_size_inch    351 non-null    float64
 12  display_type         351 non-null    object
 13  color                351 non-null    object
dtypes: bool(2), float64(1), int64(4), object(7)
memory usage: 33.7+ KB

In [142]:
df.describe()

,ram,storage_capacity_gb,graphics_capacity,price,display_size_inch
count,351.000000,351.000000,351.000000,3.510000e+02,351.000000
mean,12.854701,653.094017,0.361823,1.419777e+05,15.014530
std,10.586189,553.158195,2.744891,1.194537e+05,1.020302
min,4.000000,128.000000,-1.000000,2.880000e+04,10.100000
25%,8.000000,512.000000,-1.000000,6.725000e+04,14.000000
50%,8.000000,512.000000,-1.000000,9.500000e+04,15.600000
75%,16.000000,512.000000,-1.000000,1.690000e+05,15.600000
max,128.000000,8192.000000,16.000000,1.095000e+06,17.300000

In [143]:
df.isnull().sum()

brand_name             0
name                   0
processor_type         0
processor_brand        0
generations            0
ram                    0
storage_capacity_gb    0
have_ssd               0
have_hdd               0
graphics_capacity      0
price                  0
display_size_inch      0
display_type           0
color                  0
dtype: int64

In [144]:
df = df.drop(["name","color"], axis=1)

In [145]:
X = df.drop("price", axis=1)
y = df["price"]

In [146]:
categorical_cols = X.select_dtypes(include="object").columns
numeric_cols = X.select_dtypes(exclude="object").columns

In [147]:
from sklearn.preprocessing import StandardScaler

In [148]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", StandardScaler(), numeric_cols)
    ]
)

In [149]:
model = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

In [150]:
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

In [151]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [152]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['brand_name', 'processor_type', 'processor_brand', 'generations',
       'display_type'],
      dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['ram', 'storage_capacity_gb', 'have_ssd', 'have_hdd',
       'graphics_capacity', 'display_size_inch'],
      dtype='object'))])),
                ('model',
                 RandomForestRegressor(n_estimators=300, random_state=42))])

In [153]:
pred = pipeline.predict(X_test)

In [154]:
score = r2_score(y_test, pred)

print("Model Accuracy (R2 Score):", score)

Model Accuracy (R2 Score): 0.9719569895904107

In [155]:
joblib.dump(pipeline, "laptop_price_model.pkl")
print("Model + Encoder + Scaler saved successfully!")

Model + Encoder + Scaler saved successfully!

In [156]:
sample_data = {
    "brand_name": ["lenovo"],
    "processor_brand": ["intel"],
    "processor_type": ["i5"],
    "generations": ["11th"],
    "ram": [8],
    "storage_capacity_gb": [512],
    "have_ssd": [1],
    "have_hdd": [0],
    "graphics_capacity": [4],
    "display_size_inch": [15.6],
    "display_type": ["FHD"]
}

In [ ]:
model = joblib.load("laptop_price_model.pkl")

sample_df = pd.DataFrame(sample_data)
predicted_price = model.predict(sample_df)

print("Predicted Laptop Price:", predicted_price[0])

Predicted Laptop Price: 109553.99999999999